export {
  AdminDashboardPage,
  AdminHomePage,
  AdminLayoutPage,
  AdminLoginPage,
  AdminUsersPage,
  CheckoutPage,
  HomePage,
  LoginPage,
  NotFoundPage,
  PhoneDetailPage,
  ProfileHomePage,
  ProfileLayoutPage,
  ProfileSettingsPage,
  RegisterPage,
  ResetPasswordPage,
  SearchPage,
  VerifyEmailPage,
  WishlistPage,
} from './Placeholders'
